### ISSUE TITLE
training is too low in single machine multi ranks

### ISSUE THREAD

**Issue by FlyCarrot** [deeplearning-wisc/vos#17]
When I train under the condition of single machine and multi ranks, the training speed is very slow. 
But single rank is ok.
Is anyone the same as me？

**Comment by d12306** [comment]
@FlyCarrot , can you provide the command line? we can take a look at it.

**Comment by FlyCarrot** [comment]
> 

I just use the standard training command and config file in README, but I found that after 12000 iters of training and it starts the VOS algorithm, the iteration speed will be slower and slower, when I synchronize with 8 ranks.
If you have tried multi ranks synchronization and do not have this problem, maybe there is a problem with my environment.
Thanks for your reply.

**Comment by d12306** [comment]
hi, @FlyCarrot , thanks for the information! I checked the experimental logs, it seems like i used the four gpus to run the vos experiments. yes, the vos indeed will prolong the training time because sampling using the torch.distributions package takes some effort on the CPU side. the normal training time on my machine will be 4 hours in 4 2080 Ti(s). i guess using 8 gpus will create additional latency for the data transfer between the cpu and gpu compared to using 4 gpus. you can try that config real quick. if that does not reduce the training time, then it probably is because of your local machine. :)

**Comment by FlyCarrot** [comment]
> hi, @FlyCarrot , thanks for the information! I checked the experimental logs, it seems like i used the four gpus to run the vos experiments. yes, the vos indeed will prolong the training time because sampling using the torch.distributions package takes some effort on the CPU side. the normal training time on my machine will be 4 hours in 4 2080 Ti(s). i guess using 8 gpus will create additional latency for the data transfer between the cpu and gpu compared to using 4 gpus. you can try that config real quick. if that does not reduce the training time, then it probably is because of your local machine. :)

I just use 4 gpus to train and it works well,  thanks for you reply.
Maybe there are some invisible bugs in 8 GPUs sync time, I think this issue can be closed temporarily.
