### ISSUE TITLE
Test Result

### ISSUE THREAD

**Issue by AmingWu** [deeplearning-wisc/vos#9]
Dear Authors,

this is the evaluation results based on VOC dataset. The results are not consistent with the given results in the paper.

![QQ截图20220227151827](https://user-images.githubusercontent.com/38445175/155872672-b8549465-6da4-4c56-a522-983d9aeda1af.png)

I first run     python apply_net.py --dataset-dir /data1/user/vos/VOC_0712_converted --test-dataset voc_custom_val --config-file VOC-Detection/faster-rcnn/vos.yaml --inference-config Inference/standard_nms.yaml --random-seed 0 --image-corruption-level 0 --visualize 0.

Then I run   python apply_net.py --dataset-dir /data1/user/COCO2017/datasets/coco --test-dataset coco_ood_val --config-file VOC-Detection/faster-rcnn/vos.yaml --inference-config Inference/standard_nms.yaml --random-seed 0 --image-corruption-level 0 --visualize 0.

Finally, I run  CUDA_VISIBLE_DEVICES=4 python voc_coco_plot.py --name vos --thres xxx --energy 1 --seed 0.

Could you give me some advice? Thank you.

**Comment by d12306** [comment]
hi, @AmingWu , thanks for trying out code out!
I tested again on my machine using the model_final_vos_resnet_voc.pth, and I get the following results.
![image](https://user-images.githubusercontent.com/42554178/155894441-da858aae-b70a-4668-9881-60de1f38622a.png)
Not sure which model are you using?

Also I noticed that you get a threshold of 0.5575 and I get a threshold of 0.5831. That means the evaluation on in-distribution data might be wrong somewhere. Not sure whether this is caused by randomness.

It is better you can try three different seeds to see the averaged results.

**Comment by AmingWu** [comment]
Thank you. I will try again. Could you interpret the meaning of the value 16872 and 1234? My result is 18069 and 1459.

**Comment by d12306** [comment]
@AmingWu , the meaning of these numbers are the amount of in-distribution and OOD objects for evaluation.

**Comment by d12306** [comment]
feel free to reopen the issue if you have further questions!
